[pytest]
filterwarnings =
    error
addopts =
    "--cov=src"
    "--cov-report=term-missing"
    "-r a"
markers =
    remote: Tests which need remote access
    local: Tests which can be run locally
